// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gajiesdyzujtkycdowbb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdhamllc2R5enVqdGt5Y2Rvd2JiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcxODkwMjEsImV4cCI6MjA3Mjc2NTAyMX0.wQnERaGKhfr8rDROeAQnRTH394PWynpebsP3lb9YuTw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});